---
# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true

hooks:
  - _build/hooks.py

repo_url: https://github.com/dokku/tutorials

site_dir: tutorials
site_name: Dokku Tutorials
site_url: https://dokku.com/tutorials/

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dokku/dokku
    - icon: fontawesome/solid/bug
      link: https://github.com/dokku/dokku/issues
    - icon: fontawesome/brands/discord
      link: https://discord.gg/YQjANGMZvu
    - icon: fontawesome/brands/slack
      link: https://slack.dokku.com/
    - icon: fontawesome/solid/hashtag
      link: https://webchat.libera.chat/?channels=dokku
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dokku
    - icon: fontawesome/solid/comments
      link: https://github.com/dokku/dokku/discussions
    - icon: fontawesome/solid/cart-shopping
      link: https://dokku.dpdcart.com/cart/add?product_id=217344&method_id=236878

theme:
  custom_dir: docs/_overrides
  favicon: assets/favicons/favicon-96x96.png
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - search.highlight
  homepage: https://dokku.com
  icon:
    admonition:
      tip: fontawesome/solid/wand-magic-sparkles
  logo: assets/dokku-logo.svg
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

plugins:
  - search
  - exclude:
      glob:
        - _build/Dockerfile
        - _build/entrypoint
        - _build/requirements.txt

extra_css:
  - assets/extra.css

nav:
  - Docs:
    - https://dokku.com/docs/getting-started/installation/
  - Pro:
    - https://pro.dokku.com/docs/getting-started/
  - Blog:
    - https://dokku.com/blog/
  - Tutorials:
    - index.md
    - Apps:
      - apps/deploying-gogs-to-dokku.md
    - Automation:
      - automation/automating-dokku-setup.md
    - Network:
      - network/connect-to-host-processes.md
    - Plugins:
      - plugins/creating-a-datastore-plugin.md
    - Other:
      - other/deploying-to-k3s.md
      - other/deploying-an-image-without-a-registry.md
      - other/run-on-external-volume.md
      - other/using-websockets-in-dokku.md
  - Purchase Dokku Pro:
    - https://dokku.dpdcart.com/cart/add?product_id=217344&method_id=236878
