#!/usr/bin/env bash
set -eo pipefail

write-mkdocs() {
  if [[ -f /usr/src/source/_build/write-mkdocs ]]; then
    if ! poetry run -- /usr/src/source/_build/write-mkdocs; then
      exit 0
    fi
  fi
}

main() {
  declare CMD="$1" ARGS=("${@:2}")

  if [[ "$CMD" == "build" ]]; then
    write-mkdocs
    echo "----> Executing mkdocs build"
    poetry run -- mkdocs build
    site_dir="$(grep site_dir mkdocs.yml | awk '{print $2}')"
    cp -r "/usr/src/app/${site_dir}" "/usr/src/source/${site_dir}"

    return $?
  fi

  if [[ "$CMD" == "serve" ]]; then
    write-mkdocs
    poetry run -- mkdocs serve -a 0.0.0.0:3487
    return $?
  fi

  "$CMD" "${ARGS[@]}"
}

main "$@"
